"""Wealthsimple portfolio value via SnapTrade — session request: "import
portfolio value from wealthsimple into my dashboard." Wealthsimple has
no public API of its own; SnapTrade is the account-aggregation layer
several consumer portfolio-tracker apps (Blossom included) already use
to connect to it. Read-only access to an account already connected
through SnapTrade's own hosted portal (never handled here — connecting
a brokerage means logging into Wealthsimple itself, which has to happen
in the user's own browser via SnapTrade's flow, not in app code).

SNAPTRADE_CLIENT_ID/SNAPTRADE_CONSUMER_KEY identify this app to
SnapTrade; SNAPTRADE_USER_ID/SNAPTRADE_USER_SECRET identify the
specific connected SnapTrade user (obtained via
authentication.reset_snap_trade_user_secret against an existing
SnapTrade account that already had Wealthsimple connected — not
generated by registering a fresh user here).
"""

from datetime import date, timedelta

import streamlit as st
from snaptrade_client import SnapTrade

import data_health
import persisted_state

# Wealthsimple's own account names, simplified for the kiosk — session
# request. PERSONAL specifically renamed to what it's actually used
# for. Only these four ever get their own balance row in fetch_
# portfolio's account breakdown, per explicit session request to only
# show the top 4 there — MSB (a cash/spending sub-account, not an
# investment one) stays out of that specific breakdown, though TOTAL
# VALUE's own total still includes it (that number is real net worth,
# not just "these 4 accounts"). The activity feed is a separate list
# with its own separate account-name map (see _ACTIVITY_DISPLAY_NAMES
# below) — MSB does earn a spot there, since day-to-day banking
# activity is exactly the kind of thing an activity feed is for.
ACCOUNT_DISPLAY_NAMES = {
    "Wealthsimple Trade FHSA": "FHSA",
    "Wealthsimple Trade TFSA": "TFSA",
    "Wealthsimple Trade RRSP": "RRSP",
    "Wealthsimple Trade PERSONAL": "EMERGENCY FUND",
}

_last_good_portfolio: dict | None = None
_last_good_changes: dict | None = None
# Set whenever fetch_portfolio's underlying call fails, so the page can
# show what actually went wrong instead of one generic "not configured
# or unreachable" message covering both "secrets are missing" and "a
# real API call failed" — those need different fixes, and conflating
# them was exactly what made a real live outage hard to diagnose
# without direct access to this app's own server logs.
_last_error: str | None = None


def _client() -> SnapTrade | None:
    client_id = st.secrets.get("SNAPTRADE_CLIENT_ID")
    consumer_key = st.secrets.get("SNAPTRADE_CONSUMER_KEY")
    if not client_id or not consumer_key:
        return None
    return SnapTrade(consumer_key=consumer_key, client_id=client_id)


def last_error() -> str | None:
    """The most recent real fetch failure's own message, or None if
    the last attempt succeeded (or nothing's been tried yet)."""
    return _last_error


class _NotConfigured(Exception):
    """Raised (not just a bare None return) specifically for missing
    secrets, so fetch_portfolio can tell "nothing's configured yet"
    apart from a real API failure without needing two separate return
    channels through a cached function."""


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_portfolio_raw() -> dict | None:
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        missing = [
            n for n, v in (
                ("SNAPTRADE_CLIENT_ID", st.secrets.get("SNAPTRADE_CLIENT_ID")),
                ("SNAPTRADE_CONSUMER_KEY", st.secrets.get("SNAPTRADE_CONSUMER_KEY")),
                ("SNAPTRADE_USER_ID", user_id),
                ("SNAPTRADE_USER_SECRET", user_secret),
            ) if not v
        ]
        raise _NotConfigured(f"missing secret(s): {', '.join(missing)}")

    resp = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret)

    # Multiple currencies genuinely can't just be added together — kept
    # separate rather than silently mixed, or converted through a live
    # FX rate this module has no real need to depend on for what's
    # currently just one near-zero USD sub-account. total_cad is the
    # headline number; other_currency_totals holds anything else, shown
    # alongside it rather than folded in.
    #
    # Grouped by account name (not one row per SnapTrade account) —
    # Wealthsimple splits each registered account type into several
    # SnapTrade sub-accounts (e.g. two separate "TFSA" entries), which
    # read as a mystery duplicate rather than useful detail. A reader
    # thinks in terms of "my TFSA," not which specific sub-account
    # SnapTrade happened to split it into.
    grouped: dict[str, dict] = {}
    total_cad = 0.0
    other_currency_totals: dict[str, float] = {}
    for acct in resp.body:
        balance = (acct.get("balance") or {}).get("total")
        if not balance or balance.get("amount") is None:
            continue
        amount, currency = balance["amount"], balance.get("currency", "CAD")
        if amount == 0:
            continue  # empty sub-accounts SnapTrade auto-detects (crypto/MSB shells etc.) — nothing to show
        name = acct.get("name", "Account")
        entry = grouped.setdefault(name, {"name": name, "amount": 0.0, "currency": currency})
        entry["amount"] += amount
        if currency == "CAD":
            total_cad += amount
        else:
            other_currency_totals[currency] = other_currency_totals.get(currency, 0.0) + amount

    # Only the four renamed/tracked accounts (see ACCOUNT_DISPLAY_NAMES)
    # are surfaced by name — total_cad above already summed every real
    # account, MSB included, so it stays an accurate total even though
    # MSB itself never appears in this list.
    accounts = sorted(
        (
            {"name": ACCOUNT_DISPLAY_NAMES[a["name"]], "amount": a["amount"], "currency": a["currency"]}
            for a in grouped.values()
            if a["name"] in ACCOUNT_DISPLAY_NAMES
        ),
        key=lambda a: a["amount"],
        reverse=True,
    )
    return {"total_cad": total_cad, "other_currency_totals": other_currency_totals, "accounts": accounts}


def fetch_portfolio() -> dict | None:
    global _last_good_portfolio, _last_error
    try:
        result = _fetch_portfolio_raw()
    except _NotConfigured as e:
        _last_error = str(e)
        return _last_good_portfolio
    except Exception as e:
        # Deliberately the exception's own str(), not just its class
        # name — SnapTrade's ApiException includes the actual HTTP
        # status/reason (e.g. "401 Unauthorized"), which is the one
        # piece of information that actually tells us what to fix,
        # versus a generic "SnapTrade not configured or unreachable"
        # message that reads identically whether the problem is a
        # missing secret or an expired one.
        _last_error = f"{type(e).__name__}: {e}"
        return _last_good_portfolio
    _last_error = None
    if result is not None:
        _last_good_portfolio = result
        data_health.record_success("portfolio")
    return result if result is not None else _last_good_portfolio


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_history_by_account() -> dict[str, list[tuple[str, float]]] | None:
    """{account name -> [(date_str, total_value), ...] sorted oldest
    first} — full CAD daily balance history (get_account_balance_history)
    per account, grouped/summed by name the same way fetch_portfolio
    groups its own live totals (see that function's own comment on why:
    Wealthsimple splits one registered account into several SnapTrade
    sub-accounts). This is the one shared fetch every period's % change
    below is computed from, rather than each period hitting the API
    separately.

    Each sub-account's own history is clamped to its own
    sync_status.transactions.first_transaction_date (get_user_account_
    details) before being merged in — confirmed live this matters:
    Wealthsimple represented an account restructuring as a SECOND
    sub-account sharing the exact same display name, and the OLD one's
    balance history (dating back over a year, since drained toward $0
    as real money moved to the new one) was getting merged in as if it
    were this same account's own continuous history, producing a fake
    ~-66% "6-month change" from a balance that was never really lost.
    Clamping each sub-account to where its own transaction awareness
    actually starts keeps history from before a restructuring like
    that out of the merged series entirely, rather than misreading it
    as a loss."""
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        return None

    accounts = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret).body
    by_name: dict[str, dict[str, float]] = {}
    for acct in accounts:
        balance = (acct.get("balance") or {}).get("total")
        if not balance or not balance.get("amount") or balance.get("currency") != "CAD":
            continue
        try:
            hist = client.account_information.get_account_balance_history(
                user_id=user_id, user_secret=user_secret, account_id=acct["id"]
            )
        except Exception:
            continue
        if hist.body.get("currency") != "CAD":
            continue
        points = hist.body.get("history") or []
        if not points:
            continue

        first_trusted_date = None
        try:
            details = client.account_information.get_user_account_details(
                user_id=user_id, user_secret=user_secret, account_id=acct["id"]
            )
            first_trusted_date = details.body.get("sync_status", {}).get("transactions", {}).get(
                "first_transaction_date"
            )
        except Exception:
            pass

        name = acct.get("name", "Account")
        by_date = by_name.setdefault(name, {})
        for p in points:
            if first_trusted_date and p["date"] < first_trusted_date:
                continue
            by_date[p["date"]] = by_date.get(p["date"], 0.0) + float(p["total_value"])

    if not by_name:
        return None
    return {name: sorted(by_date.items()) for name, by_date in by_name.items()}


_last_good_value_history: list[float] | None = None


def fetch_value_history(days: int = 180) -> list[float] | None:
    """Daily total portfolio value (every real account, same scope as
    fetch_portfolio's own total_cad) over the trailing `days` — for a
    quick trend sparkline, not a precise figure, so a date before some
    account's own history begins just sums whatever's actually
    available for that date rather than being excluded outright (unlike
    _period_change_pct's stricter all-or-nothing inclusion for a real %
    number). Falls back to the last successful result on any failure —
    see this module's own warm_cache/cached_value_history for why."""
    global _last_good_value_history
    try:
        series_by_account = _fetch_history_by_account()
    except Exception:
        return _last_good_value_history
    if not series_by_account:
        return _last_good_value_history

    cutoff = (date.today() - timedelta(days=days)).isoformat()
    totals: dict[str, float] = {}
    for points in series_by_account.values():
        for d, v in points:
            if d < cutoff:
                continue
            totals[d] = totals.get(d, 0.0) + v
    if len(totals) < 2:
        return _last_good_value_history
    result = [v for _, v in sorted(totals.items())]
    _last_good_value_history = result
    return result


def _period_change(
    series_by_account: dict[str, list[tuple[str, float]]], lookback_days: int | None, live_total: float | None
) -> dict | None:
    """{"pct", "amount"} change from lookback_days ago (or, if None,
    from Jan 1 of the current year — YTD) to now. An account whose own
    history doesn't reach back that far is excluded from BOTH ends of
    this specific period's calculation, not just the "then" side —
    counting a newly-opened/newly-funded account's balance as pure
    "growth" over a window it didn't exist for would overstate real
    investment performance with new deposits. live_total (the freshest
    live read, see fetch_portfolio) replaces the "now" side ONLY when
    every single account qualified for this period — otherwise it would
    double-count accounts fetch_portfolio includes that this period's
    stricter inclusion just excluded, so the latest point each
    qualifying account's own history has is used instead (at most a day
    or two stale, which doesn't meaningfully matter over a 6-month/YTD
    window). Returns both pct and the raw dollar amount from the SAME
    start/end totals — morning_briefing.py's meaningful-change gating
    needs both together (a dollar floor AND a percent floor), not two
    separately-fetched numbers that could drift out of sync with each
    other on a fast-moving day."""
    if not series_by_account:
        return None
    today = date.today()
    target = date(today.year, 1, 1) if lookback_days is None else today - timedelta(days=lookback_days)
    target_str = target.isoformat()

    start_total = 0.0
    end_total = 0.0
    included = 0
    for points in series_by_account.values():
        if not points or points[0][0] > target_str:
            continue  # account's own history doesn't reach back to the lookback point — exclude, not "grew from $0"
        start_value = None
        for d, v in points:
            if d <= target_str:
                start_value = v
            else:
                break
        if start_value is None:
            continue
        start_total += start_value
        end_total += points[-1][1]
        included += 1

    if included == 0 or start_total == 0:
        return None
    if live_total is not None and included == len(series_by_account):
        end_total = live_total
    return {"pct": (end_total - start_total) / start_total * 100, "amount": end_total - start_total}


def fetch_period_change(days: int) -> dict | None:
    """{"pct", "amount"} change over the trailing `days` — public,
    arbitrary-lookback sibling to fetch_changes()'s fixed 1d/6m/ytd
    windows, for morning_briefing.py's own day/week/month meaningful-
    change check. Same account-inclusion care as fetch_changes (see
    _period_change's own docstring), same last-successful-fetch
    fallback as every other public function here."""
    global _last_good_period_changes
    try:
        series_by_account = _fetch_history_by_account()
    except Exception:
        return _last_good_period_changes.get(days) if _last_good_period_changes else None
    if series_by_account is None:
        return _last_good_period_changes.get(days) if _last_good_period_changes else None
    portfolio = fetch_portfolio()
    live_total = portfolio["total_cad"] if portfolio else None
    result = _period_change(series_by_account, days, live_total)
    if result is not None:
        _last_good_period_changes = _last_good_period_changes or {}
        _last_good_period_changes[days] = result
    return result


_last_good_period_changes: dict[int, dict] | None = None

# Session request: "for the portfolio page, can you make it a better
# system so that there's no issues? ... right now we're just sourcing
# the change percent from SnapTrade, aren't we? So can we instead
# outsource it by caching yesterday's result and then comparing
# yesterday's result to today's result." A real, live-confirmed reason
# behind the ask: _fetch_history_by_account's own per-account balance
# history from SnapTrade already had ONE documented incident of a
# stale/restructured sub-account's history bleeding into a period
# change (see that function's own docstring, "a fake ~-66% '6-month
# change'"), and checked live right now, the SAME class of thing is
# happening again — 6-month reads -77% and YTD reads -80%, neither
# remotely real for an account that's moved a few hundred dollars this
# whole session. daily_change() below sidesteps that entire fragile
# per-account-history/first-transaction-date reconciliation for the
# ONE window this was specifically asked about (today's change) by not
# depending on SnapTrade's own historical balance endpoint at all —
# just fetch_portfolio's own live total, which has been reliable all
# session, compared against a value THIS APP recorded itself yesterday.
# 6-month/YTD still use the old mechanism (a much longer real history
# than a same-day cache could ever provide) — out of scope for what
# was actually asked, and a real known limitation worth living with
# rather than silently also "fixing" with something equally fragile.
_PORTFOLIO_SNAPSHOT_HISTORY_DAYS = 14  # bounded rolling window — only "yesterday" is used today, but this leaves real headroom for a future week-over-week feature built the same reliable way, at near-zero storage cost
_portfolio_snapshots: dict[str, float] = persisted_state.load("portfolio_daily_snapshots", {})


def _record_daily_snapshot(total_cad: float, today: date) -> None:
    """Idempotent — only the FIRST successful fetch_portfolio() of each
    calendar day actually writes anything (checked by date key, not a
    separate "have we run today" flag), so every later call the same
    day is a no-op regardless of how many different callers invoke
    daily_change() below. That first-of-the-day value becomes
    TOMORROW's "yesterday" baseline."""
    global _portfolio_snapshots
    today_str = today.isoformat()
    if today_str in _portfolio_snapshots:
        return
    _portfolio_snapshots[today_str] = total_cad
    if len(_portfolio_snapshots) > _PORTFOLIO_SNAPSHOT_HISTORY_DAYS:
        del _portfolio_snapshots[min(_portfolio_snapshots)]
    persisted_state.save("portfolio_daily_snapshots", _portfolio_snapshots)


def daily_change() -> dict | None:
    """{"pct", "amount", "baseline_date"} — today's real live total
    (fetch_portfolio, unaffected by any SnapTrade account-history
    fragility) against OUR OWN recorded snapshot from yesterday (see
    _record_daily_snapshot). None if today's own live total isn't
    available, or there's no real snapshot from yesterday specifically
    to compare against — e.g. the very first day this ran at all, or a
    genuine full day with zero app renders (this kiosk reruns every 5s,
    so that would itself mean something else was already badly wrong) —
    never a guessed or partial number standing in for a real one."""
    portfolio = fetch_portfolio()
    if not portfolio or portfolio.get("total_cad") is None:
        return None
    live_total = portfolio["total_cad"]
    today = date.today()
    _record_daily_snapshot(live_total, today)
    baseline_date = today - timedelta(days=1)
    baseline = _portfolio_snapshots.get(baseline_date.isoformat())
    if not baseline:
        return None
    return {
        "pct": (live_total - baseline) / baseline * 100,
        "amount": live_total - baseline,
        "baseline_date": baseline_date.isoformat(),
    }


# Real, human-meaningful events only — get_account_activities also
# returns PORTFOLIO_INVESTMENT/WRITE_OFF/FEE rows from Automated
# Investing's own internal rebalancing, confirmed live these carry no
# real description (the API's own "description" field is literally
# just the type name, e.g. "PORTFOLIO_INVESTMENT") and are usually
# penny-sized — noise, not something the user did or would care to see.
_ACTIVITY_TYPES = {"CONTRIBUTION", "WITHDRAWAL", "BUY", "SELL", "DIVIDEND", "INTEREST"}
_ACTIVITY_LIMIT_PER_ACCOUNT = 20

# Session request: "if SnapTrade gives you access to my day to day
# banking, make sure that... you put that in the transaction log."
# Checked live: MSB's own activity data is real — WITHDRAWAL/
# CONTRIBUTION/INTEREST, real amounts and dates — but SnapTrade never
# hands back a merchant/payee name for it (the API's own "description"
# field is literally just "Withdrawal of $17.00," nothing more
# specific), so this can show THAT money moved and how much, never WHO
# it went to or came from — no "Rogers" in here, just the number.
# Deliberately its own dict, not an addition to ACCOUNT_DISPLAY_NAMES —
# that one also drives fetch_portfolio's own 4-tile balance breakdown
# (session request: "only show the top 4 accounts"), which this isn't
# touching; MSB earns a spot in the activity feed specifically, not a
# 5th balance tile nobody asked for.
_ACTIVITY_DISPLAY_NAMES = {**ACCOUNT_DISPLAY_NAMES, "Wealthsimple Trade MSB": "Daily Banking"}

# Follow-up session request: "identify what accounts these are... mark
# them appropriately so the AI knows what's being spent." All three
# real MSB accounts share the exact same SnapTrade account NAME
# ("Wealthsimple Trade MSB"), so the plain name-keyed dict above can't
# tell them apart — this keys off the actual account ID instead, which
# doesn't change even as each account's own balance moves day to day.
# User-supplied ground truth, matched live against each account's
# CURRENT real balance at the time this was set up: $209.85 =
# spending, $100.97 = bills, $137.43 = gas. Takes priority over the
# generic "Daily Banking" label above for these three specific
# accounts; any OTHER/future MSB account not in this map still falls
# back to that generic label rather than being silently dropped.
_MSB_ACCOUNT_LABELS = {
    "8f0ff7ea-d972-4719-b900-f7b452ba9984": "Spending",
    "97ae16f7-c4a4-4acc-9ef6-6eaf4deb1ceb": "Bills",
    "e8611574-696b-44c3-94c4-4bf85f21b078": "Gas",
}

_last_good_activities: list[dict] | None = None


def _mark_internal_transfers(activities: list[dict]) -> None:
    """Mutates `activities` in place, setting is_transfer=True on any
    WITHDRAWAL/CONTRIBUTION pair that's really money moving between two
    of Brayden's own tracked accounts, not genuine spending or income.
    Session request: "any withdrawals from that account that are not
    being deposited into an investment account is me spending" — the
    real risk this guards against: a transfer from Spending into, say,
    the Gas account would otherwise look exactly like a real $130
    spend followed by $130 of unexplained income, double-counting one
    real dollar as two fake events.

    Matched on an EXACT trade_date timestamp (down to the millisecond,
    as SnapTrade returns it) plus an exactly equal |amount|, between
    two DIFFERENT accounts — confirmed live against real data that a
    genuine internal transfer's two ledger legs share the identical
    instant, not just the same day (e.g. a real $129.52 Spending
    withdrawal and a $129.52 Gas contribution both stamped
    2026-08-13T10:35:32.765000Z, to the microsecond). A same-day-only
    match would be looser than what the real data actually supports
    and risks a false match between two genuinely unrelated same-day
    transactions; this doesn't take that risk.

    One-to-one pairing (each contribution can satisfy at most one
    withdrawal) via a plain used-set, not a many-to-many match — three
    unrelated transactions that happen to share both a timestamp and
    an amount would be exceptionally unlikely in practice, and even
    then this just pairs the first two, leaving the third correctly
    unmatched rather than over-matching."""
    contributions = [a for a in activities if a["type"] == "CONTRIBUTION"]
    used_ids = set()
    for w in activities:
        if w["type"] != "WITHDRAWAL":
            continue
        for c in contributions:
            if id(c) in used_ids or c["account"] == w["account"]:
                continue
            if c["date"] == w["date"] and abs(c["amount"]) == abs(w["amount"]):
                used_ids.add(id(c))
                w["is_transfer"] = True
                c["is_transfer"] = True
                break


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_activities_raw() -> list[dict] | None:
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        return None

    accounts = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret).body
    activities = []
    for acct in accounts:
        # The four tracked investment accounts plus MSB — labeled by
        # its own specific purpose when known (_MSB_ACCOUNT_LABELS),
        # generic "Daily Banking" otherwise (_ACTIVITY_DISPLAY_NAMES).
        # Everything else (a closed shell sub-account, CRYPTO,
        # CORPORATE) stays excluded.
        if acct.get("name") == "Wealthsimple Trade MSB":
            display_name = _MSB_ACCOUNT_LABELS.get(acct.get("id"), "Daily Banking")
        else:
            display_name = _ACTIVITY_DISPLAY_NAMES.get(acct.get("name"))
        if display_name is None:
            continue
        try:
            resp = client.account_information.get_account_activities(
                account_id=acct["id"], user_id=user_id, user_secret=user_secret, limit=_ACTIVITY_LIMIT_PER_ACCOUNT
            )
        except Exception:
            continue
        body = resp.body
        items = body.get("data", body) if isinstance(body, dict) else body
        for item in items or []:
            activity_type = item.get("type")
            amount, trade_date = item.get("amount"), item.get("trade_date")
            if activity_type not in _ACTIVITY_TYPES or amount is None or not trade_date:
                continue
            # Raw type + ticker only — session feedback: the old plain
            # sentence ("Invested $18.00 · RRSP · Jul 16") read as an
            # undifferentiated wall of gray text on the kiosk, no way to
            # tell a dividend from a withdrawal without reading every
            # word. Presentation (the colored category tag, and how
            # each type's own extra detail gets worded) lives in
            # pages_portfolio.py — this layer just hands back facts.
            symbol_info = item.get("symbol") or {}
            symbol = symbol_info.get("symbol") or symbol_info.get("raw_symbol")
            activities.append(
                {
                    "account": display_name,
                    "type": activity_type,
                    "symbol": symbol,
                    "amount": amount,
                    "date": trade_date,
                    "is_transfer": False,
                }
            )
    _mark_internal_transfers(activities)
    return activities


def fetch_activities(limit: int = 8) -> list[dict] | None:
    """Most recent human-meaningful activity across every account,
    newest first — falls back to the last successful fetch the same
    way fetch_portfolio/fetch_changes do. Each entry's "is_transfer"
    (see _mark_internal_transfers) tells a real external spend/income
    apart from money just moving between Brayden's own tracked
    accounts — callers that care about genuine spending specifically
    (vs. a raw activity log) should check it rather than treating
    every WITHDRAWAL as money actually leaving.

    Live bug, session report: "I can't see the... section with the
    total balance... the transaction log is too long." _last_good_
    activities (what cached_activities() reads) was storing the FULL
    unsliced list here regardless of `limit` — harmless-looking with
    ~4-5 tracked accounts; today's move from Automated Investing to
    Self-Directed doubled the tracked account count to 8 (see fetch_
    positions's own docstring for the live count), each good for up to
    _ACTIVITY_LIMIT_PER_ACCOUNT=20 — confirmed live, ~170 real rows
    rendering onto a fixed-height kiosk screen (.block-container's own
    comment on 1080px viewports covers why that pushes earlier content
    off the top rather than just growing the page).

    Caches the FULL list (not `limit`-sliced) precisely because two
    genuinely different callers share this one cache through different
    `limit`s — morning_briefing.py wants 60 for real AI trend context,
    pages_portfolio.py wants far fewer to actually fit the kiosk
    screen — and whichever call happened to run last in a given rerun
    would otherwise silently overwrite the other's slice. See cached_
    activities()'s own `limit` param for the page-safe read path."""
    global _last_good_activities
    try:
        activities = _fetch_activities_raw()
    except Exception:
        return (_last_good_activities or [])[:limit]
    if activities is None:
        return (_last_good_activities or [])[:limit]
    activities.sort(key=lambda a: a["date"], reverse=True)
    _last_good_activities = activities
    # A separate SnapTrade endpoint from fetch_portfolio's own balance
    # call (see data_health.THRESHOLDS_SECONDS's own "portfolio_
    # activity" comment) — recorded here, not there, so a break
    # specific to this one doesn't hide behind "portfolio" still
    # looking healthy off the balance call alone.
    data_health.record_success("portfolio_activity")
    return activities[:limit]


def fetch_changes() -> dict | None:
    """{"1d", "6m", "ytd"} % change, each None if that specific window
    can't be computed yet. "1d" is computed independently via
    daily_change() — see that function's own docstring on why (a real
    SnapTrade per-account-history bug already corrupted 6m/ytd once,
    confirmed live doing it again right now) — so a 6m/ytd fetch
    failure can't take "1d" down with it, or vice versa; each has its
    own separate fallback. "6m"/"ytd" are still our own metric end to
    end from SnapTrade's own per-account balance history — SnapTrade
    doesn't compute period returns itself (its own return-rates
    endpoint returned 403 for this account, confirmed live) — a
    same-day cache can't stand in for genuine multi-month depth the
    way it can for "1d"."""
    global _last_good_changes
    one_day = (daily_change() or {}).get("pct")
    try:
        series_by_account = _fetch_history_by_account()
    except Exception:
        series_by_account = None
    cached = _last_good_changes or {}
    if series_by_account is None:
        return {"1d": one_day if one_day is not None else cached.get("1d"), "6m": cached.get("6m"), "ytd": cached.get("ytd")}
    result = {
        "1d": one_day,
        "6m": (_period_change(series_by_account, 182, live_total=None) or {}).get("pct"),
        "ytd": (_period_change(series_by_account, None, live_total=None) or {}).get("pct"),
    }
    _last_good_changes = result
    return result


# pages_portfolio.py's own render() used to call fetch_changes/
# fetch_value_history/fetch_activities directly — each a real SnapTrade
# call (per-account balance history, several accounts) confirmed live
# to take up to ~14s combined on a cold cache. Live bug: this page
# blocking past app.py's 5s st_autorefresh window, corrupting the
# Streamlit rerun and blending pages together on screen. warm_cache
# below is wired into app.py's toast-check loop instead (via
# fetch_throttle.run_bounded, not called directly — see that function's
# own docstring for why a plain unbounded call isn't enough on its
# own); render() now reads only the cached_* accessors, which never
# fetch anything themselves.
def cached_changes() -> dict | None:
    return _last_good_changes


def cached_value_history() -> list[float] | None:
    return _last_good_value_history


def cached_activities(limit: int = 8) -> list[dict] | None:
    """The most recent `limit` activities from the full cached list —
    see fetch_activities's own docstring for why this slices at read
    time instead of trusting whatever limit the last fetch_activities()
    caller happened to pass. Default of 8 (not fetch_activities's own
    unbounded default) is the kiosk-safe row count for pages_
    portfolio.py's fixed-height RECENT ACTIVITY tile — confirmed live
    against a real 1080px kiosk viewport with today's account count."""
    return (_last_good_activities or [])[:limit]


# Session request, the same day the account moved from Automated
# Investing to Self-Directed within each of TFSA/RRSP/FHSA: "you should
# be able to see their holdings later today when it goes through." No
# per-security breakdown existed anywhere on this page before — only
# the aggregate balance total and the activity feed's own buy/sell
# lines. get_user_account_positions is SnapTrade's own SDK method for
# this (confirmed live: flagged "deprecated" in its warning log but
# still the one that actually returns data — get_user_holdings, the
# non-deprecated sibling, returned a real 410 Gone for this account).
#
# Iterates every account ID grouped under a tracked display name (not
# just one hardcoded ID per name) for the same reason fetch_portfolio's
# own grouping does — Wealthsimple represents an account restructuring
# as a SECOND SnapTrade sub-account sharing the exact same name (see
# _fetch_history_by_account's own docstring for the first time this
# bit), confirmed live again today: TFSA/RRSP/FHSA each currently have
# both an old (closed, $0, CUSTOM_PORTFOLIO_*) and new (open,
# SELF_DIRECTED_*) sub-account under the identical name.
#
# Skips any account with a zero/missing balance (same filter fetch_
# portfolio's own grouping loop already applies) BEFORE calling
# get_user_account_positions on it, rather than calling it for every
# same-named account and discarding empty results afterward — checked
# live, this account alone currently has 23 sub-accounts across the 4
# tracked names once every past restructuring's dead $0 leftovers are
# counted (12 of those under "PERSONAL" alone), and a real SnapTrade
# response header seen during this same investigation
# (X-RateLimit-Account-Limit: 10, X-RateLimit-Account-Reset: 60) makes
# querying all 23 on every warm_cache() call a real risk, not just
# wasted calls, for a feature where a zero-balance account holding a
# real position is already an edge case rare enough not to trade a
# rate-limit exhaustion risk against.
_last_good_positions: dict[str, list[dict]] | None = None


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_positions_raw() -> dict[str, list[dict]] | None:
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        return None

    accounts = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret).body
    by_name: dict[str, list[dict]] = {}
    for acct in accounts:
        display_name = ACCOUNT_DISPLAY_NAMES.get(acct.get("name"))
        if display_name is None:
            continue
        balance = (acct.get("balance") or {}).get("total")
        if not balance or not balance.get("amount"):
            continue
        try:
            resp = client.account_information.get_user_account_positions(
                user_id=user_id, user_secret=user_secret, account_id=acct["id"]
            )
        except Exception:
            continue
        for pos in resp.body or []:
            units = pos.get("units")
            # cash_equivalent positions (a money-market/cash "position"
            # some brokerages report alongside real holdings) aren't
            # what "holdings" means here — the balance tile above
            # already covers cash. units is None/0 for a fully-closed-
            # out position some APIs still list with zero size; neither
            # is a real current holding worth a row.
            if pos.get("cash_equivalent") or not units:
                continue
            symbol_info = (pos.get("symbol") or {}).get("symbol") or {}
            symbol = symbol_info.get("symbol") or symbol_info.get("raw_symbol")
            if not symbol:
                continue
            price = pos.get("price")
            by_name.setdefault(display_name, []).append(
                {
                    "symbol": symbol,
                    "description": symbol_info.get("description"),
                    "units": float(units),
                    "price": float(price) if price is not None else None,
                    "market_value": float(units) * float(price) if price is not None else None,
                    "average_purchase_price": pos.get("average_purchase_price"),
                    "open_pnl": pos.get("open_pnl"),
                }
            )
    return by_name or None


def fetch_positions() -> dict[str, list[dict]] | None:
    """{display_name -> [{"symbol", "description", "units", "price",
    "market_value", "average_purchase_price", "open_pnl"}, ...]} for
    every tracked account that currently holds real securities (an
    account holding only cash, or none at all, simply has no key here —
    never a key mapped to an empty list). Same last-successful-fetch
    fallback as every other public function in this module."""
    global _last_good_positions
    try:
        result = _fetch_positions_raw()
    except Exception:
        return _last_good_positions
    if result is not None:
        _last_good_positions = result
        data_health.record_success("portfolio_positions")
    return result if result is not None else _last_good_positions


def cached_positions() -> dict[str, list[dict]] | None:
    return _last_good_positions


def warm_cache() -> None:
    fetch_changes()
    fetch_value_history(days=180)
    # No `limit` here — this call's only job is priming _last_good_
    # activities with the full list (see fetch_activities's own
    # docstring); the actual per-caller row count is decided at read
    # time by cached_activities's own `limit`.
    fetch_activities()
    fetch_positions()
