"""Wealthsimple portfolio value via SnapTrade — session request: "import
portfolio value from wealthsimple into my dashboard." Wealthsimple has
no public API of its own; SnapTrade is the account-aggregation layer
several consumer portfolio-tracker apps (Blossom included) already use
to connect to it. Read-only access to an account already connected
through SnapTrade's own hosted portal (never handled here — connecting
a brokerage means logging into Wealthsimple itself, which has to happen
in the user's own browser via SnapTrade's flow, not in app code).

SNAPTRADE_CLIENT_ID/SNAPTRADE_CONSUMER_KEY identify this app to
SnapTrade; SNAPTRADE_USER_ID/SNAPTRADE_USER_SECRET identify the
specific connected SnapTrade user (obtained via
authentication.reset_snap_trade_user_secret against an existing
SnapTrade account that already had Wealthsimple connected — not
generated by registering a fresh user here).
"""

from datetime import date, timedelta

import streamlit as st
from snaptrade_client import SnapTrade

import data_health

# Wealthsimple's own account names, simplified for the kiosk — session
# request. PERSONAL specifically renamed to what it's actually used
# for. Only these four are ever shown by name (account breakdown rows
# + activity feed) — MSB is a cash/spending sub-account, not an
# investment one, and TOTAL VALUE's own total still includes it (that
# number is real net worth, not just "these 4 accounts"), it's just not
# one of the four tracked/renamed accounts, per explicit session
# request to only show the top 4.
ACCOUNT_DISPLAY_NAMES = {
    "Wealthsimple Trade FHSA": "FHSA",
    "Wealthsimple Trade TFSA": "TFSA",
    "Wealthsimple Trade RRSP": "RRSP",
    "Wealthsimple Trade PERSONAL": "EMERGENCY FUND",
}

_last_good_portfolio: dict | None = None
_last_good_changes: dict | None = None
# Set whenever fetch_portfolio's underlying call fails, so the page can
# show what actually went wrong instead of one generic "not configured
# or unreachable" message covering both "secrets are missing" and "a
# real API call failed" — those need different fixes, and conflating
# them was exactly what made a real live outage hard to diagnose
# without direct access to this app's own server logs.
_last_error: str | None = None


def _client() -> SnapTrade | None:
    client_id = st.secrets.get("SNAPTRADE_CLIENT_ID")
    consumer_key = st.secrets.get("SNAPTRADE_CONSUMER_KEY")
    if not client_id or not consumer_key:
        return None
    return SnapTrade(consumer_key=consumer_key, client_id=client_id)


def last_error() -> str | None:
    """The most recent real fetch failure's own message, or None if
    the last attempt succeeded (or nothing's been tried yet)."""
    return _last_error


class _NotConfigured(Exception):
    """Raised (not just a bare None return) specifically for missing
    secrets, so fetch_portfolio can tell "nothing's configured yet"
    apart from a real API failure without needing two separate return
    channels through a cached function."""


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_portfolio_raw() -> dict | None:
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        missing = [
            n for n, v in (
                ("SNAPTRADE_CLIENT_ID", st.secrets.get("SNAPTRADE_CLIENT_ID")),
                ("SNAPTRADE_CONSUMER_KEY", st.secrets.get("SNAPTRADE_CONSUMER_KEY")),
                ("SNAPTRADE_USER_ID", user_id),
                ("SNAPTRADE_USER_SECRET", user_secret),
            ) if not v
        ]
        raise _NotConfigured(f"missing secret(s): {', '.join(missing)}")

    resp = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret)

    # Multiple currencies genuinely can't just be added together — kept
    # separate rather than silently mixed, or converted through a live
    # FX rate this module has no real need to depend on for what's
    # currently just one near-zero USD sub-account. total_cad is the
    # headline number; other_currency_totals holds anything else, shown
    # alongside it rather than folded in.
    #
    # Grouped by account name (not one row per SnapTrade account) —
    # Wealthsimple splits each registered account type into several
    # SnapTrade sub-accounts (e.g. two separate "TFSA" entries), which
    # read as a mystery duplicate rather than useful detail. A reader
    # thinks in terms of "my TFSA," not which specific sub-account
    # SnapTrade happened to split it into.
    grouped: dict[str, dict] = {}
    total_cad = 0.0
    other_currency_totals: dict[str, float] = {}
    for acct in resp.body:
        balance = (acct.get("balance") or {}).get("total")
        if not balance or balance.get("amount") is None:
            continue
        amount, currency = balance["amount"], balance.get("currency", "CAD")
        if amount == 0:
            continue  # empty sub-accounts SnapTrade auto-detects (crypto/MSB shells etc.) — nothing to show
        name = acct.get("name", "Account")
        entry = grouped.setdefault(name, {"name": name, "amount": 0.0, "currency": currency})
        entry["amount"] += amount
        if currency == "CAD":
            total_cad += amount
        else:
            other_currency_totals[currency] = other_currency_totals.get(currency, 0.0) + amount

    # Only the four renamed/tracked accounts (see ACCOUNT_DISPLAY_NAMES)
    # are surfaced by name — total_cad above already summed every real
    # account, MSB included, so it stays an accurate total even though
    # MSB itself never appears in this list.
    accounts = sorted(
        (
            {"name": ACCOUNT_DISPLAY_NAMES[a["name"]], "amount": a["amount"], "currency": a["currency"]}
            for a in grouped.values()
            if a["name"] in ACCOUNT_DISPLAY_NAMES
        ),
        key=lambda a: a["amount"],
        reverse=True,
    )
    return {"total_cad": total_cad, "other_currency_totals": other_currency_totals, "accounts": accounts}


def fetch_portfolio() -> dict | None:
    global _last_good_portfolio, _last_error
    try:
        result = _fetch_portfolio_raw()
    except _NotConfigured as e:
        _last_error = str(e)
        return _last_good_portfolio
    except Exception as e:
        # Deliberately the exception's own str(), not just its class
        # name — SnapTrade's ApiException includes the actual HTTP
        # status/reason (e.g. "401 Unauthorized"), which is the one
        # piece of information that actually tells us what to fix,
        # versus a generic "SnapTrade not configured or unreachable"
        # message that reads identically whether the problem is a
        # missing secret or an expired one.
        _last_error = f"{type(e).__name__}: {e}"
        return _last_good_portfolio
    _last_error = None
    if result is not None:
        _last_good_portfolio = result
        data_health.record_success("portfolio")
    return result if result is not None else _last_good_portfolio


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_history_by_account() -> dict[str, list[tuple[str, float]]] | None:
    """{account name -> [(date_str, total_value), ...] sorted oldest
    first} — full CAD daily balance history (get_account_balance_history)
    per account, grouped/summed by name the same way fetch_portfolio
    groups its own live totals (see that function's own comment on why:
    Wealthsimple splits one registered account into several SnapTrade
    sub-accounts). This is the one shared fetch every period's % change
    below is computed from, rather than each period hitting the API
    separately.

    Each sub-account's own history is clamped to its own
    sync_status.transactions.first_transaction_date (get_user_account_
    details) before being merged in — confirmed live this matters:
    Wealthsimple represented an account restructuring as a SECOND
    sub-account sharing the exact same display name, and the OLD one's
    balance history (dating back over a year, since drained toward $0
    as real money moved to the new one) was getting merged in as if it
    were this same account's own continuous history, producing a fake
    ~-66% "6-month change" from a balance that was never really lost.
    Clamping each sub-account to where its own transaction awareness
    actually starts keeps history from before a restructuring like
    that out of the merged series entirely, rather than misreading it
    as a loss."""
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        return None

    accounts = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret).body
    by_name: dict[str, dict[str, float]] = {}
    for acct in accounts:
        balance = (acct.get("balance") or {}).get("total")
        if not balance or not balance.get("amount") or balance.get("currency") != "CAD":
            continue
        try:
            hist = client.account_information.get_account_balance_history(
                user_id=user_id, user_secret=user_secret, account_id=acct["id"]
            )
        except Exception:
            continue
        if hist.body.get("currency") != "CAD":
            continue
        points = hist.body.get("history") or []
        if not points:
            continue

        first_trusted_date = None
        try:
            details = client.account_information.get_user_account_details(
                user_id=user_id, user_secret=user_secret, account_id=acct["id"]
            )
            first_trusted_date = details.body.get("sync_status", {}).get("transactions", {}).get(
                "first_transaction_date"
            )
        except Exception:
            pass

        name = acct.get("name", "Account")
        by_date = by_name.setdefault(name, {})
        for p in points:
            if first_trusted_date and p["date"] < first_trusted_date:
                continue
            by_date[p["date"]] = by_date.get(p["date"], 0.0) + float(p["total_value"])

    if not by_name:
        return None
    return {name: sorted(by_date.items()) for name, by_date in by_name.items()}


def fetch_value_history(days: int = 180) -> list[float] | None:
    """Daily total portfolio value (every real account, same scope as
    fetch_portfolio's own total_cad) over the trailing `days` — for a
    quick trend sparkline, not a precise figure, so a date before some
    account's own history begins just sums whatever's actually
    available for that date rather than being excluded outright (unlike
    _period_change_pct's stricter all-or-nothing inclusion for a real %
    number). None if there's not enough history to draw a real trend."""
    try:
        series_by_account = _fetch_history_by_account()
    except Exception:
        return None
    if not series_by_account:
        return None

    cutoff = (date.today() - timedelta(days=days)).isoformat()
    totals: dict[str, float] = {}
    for points in series_by_account.values():
        for d, v in points:
            if d < cutoff:
                continue
            totals[d] = totals.get(d, 0.0) + v
    if len(totals) < 2:
        return None
    return [v for _, v in sorted(totals.items())]


def _period_change_pct(
    series_by_account: dict[str, list[tuple[str, float]]], lookback_days: int | None, live_total: float | None
) -> float | None:
    """% change from lookback_days ago (or, if None, from Jan 1 of the
    current year — YTD) to now. An account whose own history doesn't
    reach back that far is excluded from BOTH ends of this specific
    period's calculation, not just the "then" side — counting a newly-
    opened/newly-funded account's balance as pure "growth" over a
    window it didn't exist for would overstate real investment
    performance with new deposits. live_total (the freshest live read,
    see fetch_portfolio) replaces the "now" side ONLY when every single
    account qualified for this period — otherwise it would double-count
    accounts fetch_portfolio includes that this period's stricter
    inclusion just excluded, so the latest point each qualifying
    account's own history has is used instead (at most a day or two
    stale, which doesn't meaningfully matter over a 6-month/YTD
    window)."""
    if not series_by_account:
        return None
    today = date.today()
    target = date(today.year, 1, 1) if lookback_days is None else today - timedelta(days=lookback_days)
    target_str = target.isoformat()

    start_total = 0.0
    end_total = 0.0
    included = 0
    for points in series_by_account.values():
        if not points or points[0][0] > target_str:
            continue  # account's own history doesn't reach back to the lookback point — exclude, not "grew from $0"
        start_value = None
        for d, v in points:
            if d <= target_str:
                start_value = v
            else:
                break
        if start_value is None:
            continue
        start_total += start_value
        end_total += points[-1][1]
        included += 1

    if included == 0 or start_total == 0:
        return None
    if live_total is not None and included == len(series_by_account):
        end_total = live_total
    return (end_total - start_total) / start_total * 100


# Real, human-meaningful events only — get_account_activities also
# returns PORTFOLIO_INVESTMENT/WRITE_OFF/FEE rows from Automated
# Investing's own internal rebalancing, confirmed live these carry no
# real description (the API's own "description" field is literally
# just the type name, e.g. "PORTFOLIO_INVESTMENT") and are usually
# penny-sized — noise, not something the user did or would care to see.
_ACTIVITY_TYPES = {"CONTRIBUTION", "WITHDRAWAL", "BUY", "SELL", "DIVIDEND", "INTEREST"}
_ACTIVITY_LIMIT_PER_ACCOUNT = 20

_last_good_activities: list[dict] | None = None


@st.cache_data(ttl=15 * 60, show_spinner=False)
def _fetch_activities_raw() -> list[dict] | None:
    client = _client()
    user_id = st.secrets.get("SNAPTRADE_USER_ID")
    user_secret = st.secrets.get("SNAPTRADE_USER_SECRET")
    if client is None or not user_id or not user_secret:
        return None

    accounts = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret).body
    activities = []
    for acct in accounts:
        # Same four tracked accounts as fetch_portfolio's own breakdown
        # (see ACCOUNT_DISPLAY_NAMES) — MSB's own activity is real but
        # isn't one of "my top 4 accounts," per explicit session request.
        display_name = ACCOUNT_DISPLAY_NAMES.get(acct.get("name"))
        if display_name is None:
            continue
        try:
            resp = client.account_information.get_account_activities(
                account_id=acct["id"], user_id=user_id, user_secret=user_secret, limit=_ACTIVITY_LIMIT_PER_ACCOUNT
            )
        except Exception:
            continue
        body = resp.body
        items = body.get("data", body) if isinstance(body, dict) else body
        for item in items or []:
            activity_type = item.get("type")
            amount, trade_date = item.get("amount"), item.get("trade_date")
            if activity_type not in _ACTIVITY_TYPES or amount is None or not trade_date:
                continue
            # Raw type + ticker only — session feedback: the old plain
            # sentence ("Invested $18.00 · RRSP · Jul 16") read as an
            # undifferentiated wall of gray text on the kiosk, no way to
            # tell a dividend from a withdrawal without reading every
            # word. Presentation (the colored category tag, and how
            # each type's own extra detail gets worded) lives in
            # pages_portfolio.py — this layer just hands back facts.
            symbol_info = item.get("symbol") or {}
            symbol = symbol_info.get("symbol") or symbol_info.get("raw_symbol")
            activities.append(
                {
                    "account": display_name,
                    "type": activity_type,
                    "symbol": symbol,
                    "amount": amount,
                    "date": trade_date,
                }
            )
    return activities


def fetch_activities(limit: int = 8) -> list[dict] | None:
    """Most recent human-meaningful activity across every account,
    newest first — falls back to the last successful fetch the same
    way fetch_portfolio/fetch_changes do."""
    global _last_good_activities
    try:
        activities = _fetch_activities_raw()
    except Exception:
        return _last_good_activities
    if activities is None:
        return _last_good_activities
    activities.sort(key=lambda a: a["date"], reverse=True)
    _last_good_activities = activities
    return activities[:limit]


def fetch_changes() -> dict | None:
    """{"1d", "6m", "ytd"} % change, each None if that specific window
    can't be computed yet (no qualifying account history). Our own
    metric end to end — SnapTrade doesn't compute period returns
    itself (its own return-rates endpoint returned 403 for this
    account, confirmed live)."""
    global _last_good_changes
    try:
        series_by_account = _fetch_history_by_account()
    except Exception:
        return _last_good_changes
    if series_by_account is None:
        return _last_good_changes
    portfolio = fetch_portfolio()
    live_total = portfolio["total_cad"] if portfolio else None
    result = {
        "1d": _period_change_pct(series_by_account, 1, live_total),
        "6m": _period_change_pct(series_by_account, 182, live_total=None),
        "ytd": _period_change_pct(series_by_account, None, live_total=None),
    }
    _last_good_changes = result
    return result
